[package]
name = "skakarlak"
version = "0.1.0"
edition = "2021"

[dependencies]
rand = "0.9.2"
rand_chacha = "0.9.0"
shakmaty = "0.27.3"
shakmaty-uci = "0.1.1"
tokio = { version = "1.37.0", features = ["full", "io-util", "macros", "sync", "time"] }
